# Generated by Django 5.0 on 2023-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_purchasehistory_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('expired', 'Expired'), ('available', 'Available')], default='available', max_length=10),
        ),
    ]
